In [5]:
import pandas as pd
import numpy as np
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

In [ ]:
path = "/content/gdrive/MyDrive/Takeo/Hotel Reviews/Hotel_Reviews.csv"
df = pd.read_csv(path)
df

In [ ]:
df.head()

In [ ]:
df.describe()

In [ ]:
df.isnull().sum()

In [21]:
# 1) How many reviewers from each nation

# Group by nationality and count reviews
review_count = df.groupby("Reviewer_Nationality")["Total_Number_of_Reviews_Reviewer_Has_Given"].count()

# sShow all answer
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)
print(review_count)

Reviewer_Nationality
                                             523
 Abkhazia Georgia                            153
 Afghanistan                                   8
 Albania                                     286
 Algeria                                     100
 American Samoa                                2
 Andorra                                      64
 Angola                                       62
 Anguilla                                      1
 Antarctica                                    3
 Antigua Barbuda                              14
 Argentina                                   517
 Armenia                                     134
 Aruba                                        31
 Australia                                 21686
 Austria                                    2412
 Azerbaijan                                  277
 Bahamas                                      32
 Bahrain                                    1592
 Bangladesh                                  151
 Barbados                                     61
 Belarus                                     192
 Belgium                                    6031
 Belize                                        8
 Benin                                         6
 Bermuda                                     103
 Bhutan                                        6
 Bolivia                                      18
 Bonaire St Eustatius and Saba                 3
 Bosnia and Herzegovina                      246
 Botswana                                     42
 Brazil                                     1865
 British Virgin Islands                       16
 Brunei                                      100
 Bulgaria                                   1314
 Burundi                                       3
 Cambodia                                     34
 Cameroon                                      9
 Canada                                     7894
 Cape Verde                                    1
 Cayman Islands                               42
 Central Africa Republic                       3
 Chile                                       334
 China                                      3400
 Cocos K I                                     2
 Colombia                                    277
 Comoros                                       1
 Congo                                         3
 Cook Islands                                  2
 Costa Rica                                  120
 Crimea                                        6
 Croatia                                    1340
 Cura ao                                      41
 Cyprus                                     1381
 Czech Republic                             2311
 Democratic Republic of the Congo              9
 Denmark                                    1724
 Djibouti                                      2
 Dominica                                     11
 Dominican Republic                           52
 East Timor                                    4
 Ecuador                                      61
 Egypt                                      2388
 El Salvador                                  24
 Equatorial Guinea                             2
 Eritrea                                       2
 Estonia                                     757
 Ethiopia                                     32
 Falkland Islands Malvinas                     6
 Faroe Islands                                16
 Fiji                                         12
 Finland                                    1829
 France                                     7296
 French Guiana                                 4
 French Polynesia                              3
 Gabon                                         7
 Gambia                                        5
 Georgia                                     294
 Germany                                    7941
 Ghana                                       145
 Gibraltar                                   380
 Greece                                     3406
 Grenada                                       3
 Guadeloupe                                    5
 Guam                                         14
 Guatemala                                    53
 Guernsey                                    543
 Guinea                                        1
 Guyana                                        5
 Haiti                                         6
 Honduras                                     22
 Hong Kong                                  3013
 Hungary                                    2185
 Iceland                                     933
 India                                      3437
 Indonesia                                  1548
 Iran                                       1086
 Iraq                                        290
 Ireland                                   14827
 Isle of Man                                 405
 Israel                                     6610
 Italy                                      6114
 Ivory Coast                                  19
 Jamaica                                      41
 Japan                                      1279
 Jersey                                      863
 Jordan                                      757
 Kazakhstan                                  281
 Kenya                                       269
 Kiribati                                      2
 Kosovo                                       72
 Kuwait                                     4920
 Kyrgyzstan                                   21
 Laos                                          9
 Latvia                                      719
 Lebanon                                    2261
 Lesotho                                       3
 Liberia                                       3
 Libya                                        72
 Liechtenstein                                20
 Lithuania                                   727
 Luxembourg                                 1359
 Macau                                       109
 Macedonia                                   282
 Madagascar                                    8
 Malawi                                       10
 Malaysia                                   1883
 Maldives                                     49
 Mali                                          5
 Malta                                      1685
 Martinique                                    5
 Mauritania                                    8
 Mauritius                                   216
 Mexico                                      592
 Moldova                                     108
 Monaco                                      250
 Mongolia                                     39
 Montenegro                                  192
 Montserrat                                    2
 Morocco                                     229
 Mozambique                                   35
 Myanmar                                      18
 Namibia                                      67
 Nepal                                        15
 Netherlands                                8772
 New Caledonia                                10
 New Zealand                                3237
 Nicaragua                                    15
 Niger                                         2
 Nigeria                                     977
 Northern Mariana Islands                      1
 Norway                                     2383
 Oman                                       1334
 Pakistan                                    916
 Palau                                         1
 Palestinian Territory                        54
 Panama                                      122
 Papua New Guinea                             14
 Paraguay                                     28
 Peru                                        118
 Philippines                                1073
 Poland                                     2891
 Portugal                                   1839
 Puerto Rico                                 180
 Qatar                                      2757
 Reunion                                       6
 Romania                                    4552
 Russia                                     3900
 Rwanda                                       13
 Saint Barts                                   3
 Saint Kitts and Nevis                         9
 Saint Lucia                                   8
 Saint Martin                                  4
 Saint Vincent Grenadines                      2
 Samoa                                         4
 San Marino                                    3
 Saudi Arabia                               8951
 Senegal                                      24
 Serbia                                     1124
 Seychelles                                   21
 Sierra Leone                                  6
 Singapore                                  3091
 Slovakia                                    903
 Slovenia                                    796
 Somalia                                       3
 South Africa                               3821
 South Korea                                1078
 South Sudan                                   2
 Spain                                      4737
 Sri Lanka                                   284
 St Maarten                                   11
 St Pierre and Miquelon                        2
 Sudan                                        51
 Suriname                                     11
 Svalbard Jan Mayen                            1
 Swaziland                                     8
 Sweden                                     3368
 Switzerland                                8678
 Syria                                        33
 Taiwan                                      923
 Tajikistan                                   16
 Tanzania                                     58
 Thailand                                   1880
 Togo                                          7
 Trinidad and Tobago                         154
 Tunisia                                      76
 Turkey                                     5444
 Turkmenistan                                  5
 Turks Caicos Islands                         14
 Tuvalu                                        1
 U S Virgin Islands                           17
 Uganda                                       47
 Ukraine                                    1102
 United Arab Emirates                      10235
 United Kingdom                           245246
 United States Minor Outlying Islands         74
 United States of America                  35437
 Uruguay                                      91
 Uzbekistan                                   20
 Vanuatu                                       8
 Vatican City                                  1
 Venezuela                                    78
 Vietnam                                     187
 Wallis and Futuna                             2
 Yemen                                        16
 Zambia                                       37
 Zimbabwe                                     51
Name: Total_Number_of_Reviews_Reviewer_Has_Given, dtype: int64

In [28]:
# Count the number of reviewers for each nationality
reviewer_count = df['Reviewer_Nationality'].value_counts()

# Nationality with the highest number of reviewers
nationality_high_count = reviewer_count.idxmax()

# Number of reviewers from that nationality
max_reviewer_count = reviewer_count.max()

#print("Reviewer count for each nationality:")
#print(reviewer_counts)

# Print the nationality with the highest number of reviewers and the count
print("The nationality with the highest number of reviewers is: ",nationality_high_count)
print("Reviewers: ", max_reviewer_count)

The nationality with the highest number of reviewers is:   United Kingdom
Reviewers:  245246

In [32]:
# b) Lowest Reviewers from which nationality

reviewer_count = df['Reviewer_Nationality'].value_counts()

nationality_low_count = reviewer_count.idxmin()
min_reviewer_count = reviewer_count.min()

print("The nationality with the lowest number of reviewers is: ",nationality_low_count)
print("Reviewers: ", min_reviewer_count)

The nationality with the lowest number of reviewers is:   Svalbard Jan Mayen
Reviewers:  1