In [ ]:
# need to ask user for a number
# ask user for how many rows needed


# number of rows is basically where iteration stops

# csv should be 3 columns
# 1st column is like 5,5,10,15,25,40,....................
# 2nd column is like 5,25,625,.................. square
# 3rd 5,125,................. cube

In [5]:
num = int(input("Enter a number: "))
row = int(input("Please enter the number of rows: "))
def col_sum():
  initial_sum = 0
  for i in range(row):
    initial_sum += num *(i+1)
  return initial_sum

def col_square():
  square_sum = 0
  for i in range(row):
    square_sum += (num + i) ** 2
  return square_sum
def col_cube():
  cube_sum = 0
  for i in range(row):
    cube_sum += (num + i) ** 3
  return cube_sum
print("The sum of the first", row, "integers starting with", num, "is", col_sum())
print("The square of the first", row, "integers starting with", num, "is", col_square())
print("The cube of the first", row, "integers starting with", num, "is", col_cube())

Enter a number: 2
Please enter the number of rows: 5
The sum of the first 5 integers starting with 2 is 30
The square of the first 5 integers starting with 2 is 90
The cube of the first 5 integers starting with 2 is 440